apiVersion: v1
kind: Service
metadata:
  name: monitoring-app
  labels:
    app: monitoring-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: monitoring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
